[package]
name = "dyhra"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "server"
path = "./src/server/main.rs"

[[bin]]
name = "client"
path = "./src/client/main.rs"

[dependencies]
bincode = "1.3.3"
macroquad = "0.4.11"
macroquad-tiled = "0.2.1"
renet = "0.0.16"
serde = { version = "1.0.204", features = ["derive"] }
