[package]
name = "dyhra"
version = "0.1.0"
edition = "2021"
license = "GPL3"
authors = ["wick3dr0se <wick3dr0se@protonmail.com>"]
repository = "https://github.com/wick3dr0se/dyhra"

[[bin]]
name = "server"
path = "src/server/main.rs"

[[bin]]
name = "client"
path = "src/client/main.rs"

[dependencies]
macroquad = "0.4.8"
macroquad-tiled = "0.2.1"
renet = "0.0.16"
shipyard = { version = "0.7.1", default-features = false, features = [
    "std",
    "proc",
] }
#egui = "0.27.2"
#egui-wgpu = { version = "0.27.2", features = ["winit"] }
#egui-winit = "0.27.2"
#wgpu = "0.20.1"
#winit = "0.30.2"